7/cmupaper/hw7proj/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('paper.urls')),
    path('admin/', admin.site.urls),
]

7/cmupaper/paper/urls.py
from django.urls import re_path

from . import views

app_name = 'paper'
urlpatterns = [
    re_path(r'^$', views.home, name='index'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^home/$', views.home, name='home'),
    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^popular_papers/$', views.popular_papers, name='popular_papers'),
    re_path(r'^new_paper/$', views.new_paper, name='new_paper'),
    re_path(r'^like/(?P<paper_id>[0-9]+)/(?P<source>\w+)/$', views.like, name='like'),
    re_path(r'^unlike/(?P<paper_id>[0-9]+)/(?P<source>\w+)/$', views.unlike, name='unlike'),
    re_path(r'^delete_paper/(?P<paper_id>[0-9]+)$', views.delete_paper, name='delete_paper'),
    re_path(r'^view_paper/(?P<paper_id>[0-9]+)$', views.view_paper, name='view_paper'),
    re_path(r'^search_view/$', views.search_view, name='search_view'),
    re_path(r'^tag_view/(?P<tag_name>\w+)$', views.tag_view, name='tag_view'),
    re_path(r'^reset/$', views.reset, name='reset'),
]

7/cmupaper/paper/models.py
"""Design choices:
1. All tables are unmanaged, as we won't use migration to create or delete
tables. This is because migration can't use some features of the database,
like [multi-column primary keys](https://stackoverflow.com/questions/4871966/make-primary-key-with-2-fields-in-django)
or [enforcing foreign key constraints](https://code.djangoproject.com/ticket/21961).
If tables are created with migration, they won't have multi-column primary keys,
for example.
2. In models for many-to-many relationships like `Tag` and `Like`, we designate
a random column as the primary key so that ORM won't generate INSERT statements
that try to insert values into the ID column, which is automatically generated
by Django if there is no primary key. This work-around may have serious
implications e.g., when you want to delete a row in a many-to-many table using
the primary key. We will write raw SQL in such cases.
"""
from django.db import models


class TagName(models.Model):
    TAG_MAX_LENGTH = 50
    tagname = models.CharField(primary_key=True, max_length=TAG_MAX_LENGTH)

    class Meta:
        managed = False
        db_table = 'tagnames'


class Tag(models.Model):
    pid = models.ForeignKey('Paper', models.DO_NOTHING, db_column='pid', primary_key=True)
    tagname = models.ForeignKey(TagName, models.DO_NOTHING, db_column='tagname')

    class Meta:
        managed = False
        db_table = 'tags'


class User(models.Model):
    USERNAME_MAX_LENGTH = 50
    PASSWORD_MAX_LENGTH = 32

    username = models.CharField(primary_key=True, max_length=USERNAME_MAX_LENGTH)
    password = models.CharField(max_length=PASSWORD_MAX_LENGTH)

    class Meta:
        managed = False
        db_table = 'users'


class Paper(models.Model):
    TITLE_MAX_LENGTH = 50
    DESCRIPTION_MAX_LENGTH = 500

    pid = models.AutoField(primary_key=True)
    username = models.ForeignKey(User, models.DO_NOTHING, db_column='username')
    title = models.CharField(max_length=TITLE_MAX_LENGTH, blank=True, null=True)
    begin_time = models.DateTimeField()
    description = models.CharField(max_length=DESCRIPTION_MAX_LENGTH, blank=True, null=True)
    data = models.TextField(blank=True, null=True)
    tag_names = models.ManyToManyField(TagName, through=Tag, through_fields=('pid', 'tagname'))
    liked_users = models.ManyToManyField(
        User,
        through='Like', through_fields=('pid', 'username'),
        related_name='liked_papers',
    )

    class Meta:
        managed = False
        db_table = 'papers'


class Like(models.Model):
    pid = models.ForeignKey(Paper, models.DO_NOTHING, db_column='pid', primary_key=True)
    username = models.ForeignKey(User, models.DO_NOTHING, db_column='username')
    like_time = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'likes'

7/cmupaper/paper/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from pytz import timezone
from datetime import timedelta
from datetime import datetime
import textract

from .constants import *
from .database_wrapper import *
from . import functions
import tempfile

"""
Utility functions
"""


def get_datetime(delta = timedelta(0)):
    """
    Get a datetime object of current time plus a timedelta
    """
    return datetime.now(timezone("US/Eastern")) + delta


def get_current_user(request):
    """
    Get the user name from a cookie.
    XXX: It's definitely not the thing you should do when you implement your own website...
    """
    cookie = request.COOKIES.get(COOKIE_USERNAME_FLAG)
    return cookie


def set_login(response, uname):
    """
    Set the user name in the cookie.
    XXX: Don't do this for production...
    """
    response.set_cookie(COOKIE_USERNAME_FLAG, uname)


def reset_login(response):
    """
    Reset the cookie
    """
    response.delete_cookie(COOKIE_USERNAME_FLAG)


def get_upload_dir_path():
    """
    Helper function to get the directory storing uploaded files.
    """
    return str(os.path.join(settings.BASE_DIR, 'media'))


def get_upload_file_path(pid):
    """
    Construct a file path based on pid
    """
    return get_upload_dir_path() + "/" + str(pid) + ".pdf"


def valid_login(request):
    """
    Validate a user has logged in by setting cookie.
    XXX: Don't do this for production
    """
    cookie = get_current_user(request)
    if cookie is None:
        return False
    return True


def append_likes_tags(conn, posts):
    """
    Utility to append like counts and tags of a given paper
    """
    likes = list()
    tag_lists = list()
    for post in posts:
        # get like count for the post
        status, likec = call_db_with_conn(conn, functions.get_likes, {'pid':int(post['pid'])})
        if status == SUCCESS:
            likes.append(int(likec))
        else:
            likes.append(0)
        # get all the tags for the post
        status, tags = call_db_with_conn(conn, functions.get_paper_tags, {'pid':int(post['pid'])})
        if status == SUCCESS:
            tag_lists.append(tags)
        else:
            tag_lists.append(list())

    for i in range(len(posts)):
        posts[i]['like'] = likes[i]
        posts[i]['tags'] = tag_lists[i]


def get_paper_dict(paper_list):
    try:
        return \
            [{'pid':x[0], 'username':x[1], 'title':x[2], 'begin_time':x[3], 'desc':x[4]} for x in paper_list]
    except (IndexError, KeyError) as e:
        print("[TA Hints] May be your return value is not in the correct format")
        raise e

"""
Views
"""


def reset(request):
    """
    Reset the database
    """
    state, res = call_db(functions.reset_db, {})
    context = dict()
    if state != SUCCESS:
        context['message'] = "Failed"
    else:
        context['message'] = "Success"
        # Delete all uploaded files
        upload_dir = get_upload_dir_path()
        for file in os.listdir(upload_dir):
            if os.path.isfile(file):
                try:
                    os.remove(file)
                except:
                    print("Can not remove file %s" % file)
    return render(request, 'paper/reset.html', context)


def logout(request):
    """
    Handle log out request
    """
    response = HttpResponseRedirect(reverse('paper:home'))
    reset_login(response)
    return response


def login(request):
    """
    Login page
    """
    if request.method == 'POST':
        try:
            uname = request.POST['username']
            pwd = request.POST['password']
        except KeyError:
            return render(request, 'paper/login.html', {'error_message': err_login})

        state, res = call_db(functions.login, {"uname":uname, "pwd":pwd})
        if state != SUCCESS:
            return render(request, 'paper/login.html',
                    {'error_message':"Incorrect username or password."})
        else:
            response = HttpResponseRedirect(reverse('paper:home'))
            set_login(response, uname)
            return response
    else:
        return render(request, 'paper/login.html', {'error_message': err_login})


def signup(request):
    """
    Signup page
    """
    if request.method == 'POST':
        uname = request.POST['username']
        pwd1 = request.POST['password1']
        pwd2 = request.POST['password2']
        if pwd1 == "" or pwd2 == "" or uname == "":
            return render(request, 'paper/signup.html', {'error_message':err_invalid_input})
        if pwd1 != pwd2:
            return render(request, 'paper/signup.html', {'error_message':"Passwords do not match."})
        state, res = call_db(functions.signup, {'uname':uname, 'pwd':pwd1})
        if state != SUCCESS:
            return render(request, 'paper/signup.html', {'error_message':"User exists"})
        response = HttpResponseRedirect(reverse('paper:home'))
        set_login(response, uname)
        return response
    elif request.method == 'GET':
        return render(request, 'paper/signup.html')


def home(request, err_msg = None):
    """
    Show the home page
    """
    # Validate login
    if not valid_login(request):
        return render(request, 'paper/login.html', {'error_message': err_login})
    uname = get_current_user(request)

    # Init context
    context = dict()
    context['username'] = get_current_user(request)
    context['error_message'] = err_msg
    context['home'] = True
    context['source'] = 'home'
    context['header_text'] = "Hello " + uname + "!"

    # Setup connection
    conn = None
    try:
        status, conn = get_db_connection()
        if status != SUCCESS:
            context['error_message'] = err_internal
            return render(request, 'paper/base_paper_list.html', context)

        # Get timeline
        status, timeline_papers = call_db_with_conn(conn, functions.get_timeline, {'uname':uname})
        if status != SUCCESS:
            context['error_message'] = err_internal
            return render(request, 'paper/base_paper_list.html', context)

        if len(timeline_papers) == 0:
            context['error_message'] = "No post posted"

        # Get liked
        status, liked_papers = call_db_with_conn(conn, functions.get_papers_by_liked, {'uname':uname})
        if status != SUCCESS:
            context['error_message'] = err_internal
            return render(request, 'paper/base_paper_list.html', context)

        if len(liked_papers) == 0:
            context['error_message2'] = "Not any liked posts"

        # Get recommendation
        status, recommend_papers = call_db_with_conn(conn, functions.get_recommend_papers, {'uname':uname})
        if status != SUCCESS:
            context['error_message'] = err_internal
            close_db_connection(conn)
            return render(request, 'paper/base_paper_list.html', context)

        if len(recommend_papers) == 0:
            context['error_message3'] = "Not any recommendation posts"

        # Get statistics
        status, num_post = call_db_with_conn(conn, functions.get_number_papers_user, {'uname':uname})
        status, num_like = call_db_with_conn(conn, functions.get_number_liked_user, {'uname':uname})
        status, num_tag = call_db_with_conn(conn, functions.get_number_tags_user, {'uname':uname})

        recommend_paper_dicts = get_paper_dict(recommend_papers)
        liked_paper_dicts = get_paper_dict(liked_papers)
        timeline_paper_dicts = get_paper_dict(timeline_papers)
        append_likes_tags(conn, recommend_paper_dicts)
        append_likes_tags(conn, liked_paper_dicts)
        append_likes_tags(conn, timeline_paper_dicts)
        context['paper_list'] = timeline_paper_dicts
        context['liked_list'] = liked_paper_dicts
        context['recommend_list'] = recommend_paper_dicts
        context['num_post'] = num_post
        context['num_like'] = num_like
        context['num_tag'] = num_tag

        response = render(request, 'paper/base_paper_list.html', context)
        return response
    finally:
        if conn is not None:
            close_db_connection(conn)


def popular_papers(request, err_msg = None):
    """
    The popular paper page
    """
    if not valid_login(request):
        return render(request, 'paper/login.html', {'error_message': "Please login."})
    # Init context
    context = dict()
    context['username'] = get_current_user(request)
    context['error_message'] = err_msg
    context['popular'] = True
    context['source'] = 'popular'
    context['header_text'] = "What's new"

    # setup connection
    conn = None
    try:
        status, conn = get_db_connection()
        if status != SUCCESS:
            context['error_message'] = err_internal
            return render(request, 'paper/base_paper_list.html', context)

        # get popular papers
        status, popular_paper_list = call_db_with_conn(conn, functions.get_most_popular_papers,
                                                   {'begin_time':get_datetime(timedelta(days=-14))})
        if status != SUCCESS:
            context['error_message'] = err_internal
            return render(request, 'paper/base_paper_list.html', context)

        if len(popular_paper_list) == 0:
            context['error_message'] = "Not any popular papers now, publish your own and become popular!"

        # get recent papers
        status, recent_paper_list = call_db_with_conn(conn, functions.get_timeline_all, {})

        if status != SUCCESS:
            context['error_message'] = err_internal
            return render(request, 'paper/base_paper_list.html', context)

        if len(recent_paper_list) == 0:
            context['error_message2'] = "Not any recent papers"

7/cmupaper/paper/templates/paper/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Paper</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'paper/style.css' %}">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  </head>

  {% block body %}
  {% endblock %}
</html>

7/cmupaper/paper/templates/paper/base_nav.html
{% extends "paper/base.html" %}
{% load static %}
{% block body %}

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'paper:home' %}">CMU Database</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <!-- <li><a href="#">User Statistics</a></li> -->
                </ul>
                <ul class="nav navbar-nav navbar-right">
                	<li>
                		<a href={% url 'paper:logout'%}>Log out</a>
                	</li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<div class="container">
{% block content %}
{% endblock %}
</div>

<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; CMU 15415/615 2016</p>
            </div>
        </div>
    </footer>

</div>

</body>

{% endblock %}

7/cmupaper/paper/templates/paper/base_paper_list.html
{% extends "paper/base_nav.html" %}
{% block content %}
<div class="page-header">
	<h1>{{ header_text }}</h1>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="list-group">
            {% if home %}
            <a href={% url 'paper:home' %} class="list-group-item active">Home</a>
            <a href={% url 'paper:popular_papers' %} class="list-group-item">Popular papers</a>
            <a href={% url 'paper:new_paper' %} class="list-group-item">Post a new paper</a>
            {% elif popular %}
            <a href={% url 'paper:home' %} class="list-group-item">Home</a>
            <a href={% url 'paper:popular_papers' %} class="list-group-item active">Popular papers</a>
            <a href={% url 'paper:new_paper' %} class="list-group-item">Post a new paper</a>
            {% elif new_paper %}
            <a href={% url 'paper:home' %} class="list-group-item">Home</a>
            <a href={% url 'paper:popular_papers' %} class="list-group-item">Popular papers</a>
            <a href={% url 'paper:new_paper' %} class="list-group-item active">Post a new paper</a>
            {% else %}
            <a href={% url 'paper:home' %} class="list-group-item">Home</a>
            <a href={% url 'paper:popular_papers' %} class="list-group-item">Popular papers</a>
            <a href={% url 'paper:new_paper' %} class="list-group-item">Post a new paper</a>
            {% endif %}
            <!-- <a href="#" class="list-group-item">Function 4</a> -->
        </div>
        {% if home %}
            <div class="page-header">
            <h4>My statistics</h4>
            </div>
            <div class = "list-group">
            <li class="list-group-item"># posts: {{ num_post }}</li>
            <li class="list-group-item"># likes: {{ num_like }}</li>
            <li class="list-group-item"># tags created: {{ num_tag }}</li>
            </div>
        {% elif popular %}
            <div class="page-header">
            <h4>Global statistics</h4>
            </div>
            <div class = "list-group">
            <li class="list-group-item">Most active user:<br> {{ active_user }}</li>
            <li class="list-group-item">Most popular tag:<br> {{ popular_tag }}</li>
            <li class="list-group-item">Most popular tag pair:<br> {{ popular_pair }}</li>
            </div>
        {% endif %}
        <div class="well">
            <h4>Blog Search</h4>
            <form role="form" action="{% url 'paper:search_view' %}" method='POST'>
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control" name="keywords" placeholder="Keywords">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>

{% if new_paper %}
    <div class="col-lg-8">
        {% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
		{% endif %}
        <div class="well">
            <form role="form" action="{% url 'paper:new_paper' %}" method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <h4>Title:</h4>
                    <textarea class="form-control" rows="1" name="title" placeholder="Less than 50 chars"></textarea>
                    <h4>Tags:</h4>
                    <textarea class="form-control" rows="1" name="tags" placeholder="tag1, tag2, tag3"></textarea>
                    <h4>Description:</h4>
                    <textarea class="form-control" rows="5" name="desc" placeholder="Less than 500 chars"></textarea>
                </div>
                <input type="file" name="post_pdf">
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% else %}
	<div class="col-lg-8">
        {% if home %}
        <div class="page_header">
	        <h2>My papers</h2>
        </div>
        {% elif popular %}
        <div class="page_header">
	        <h2>Popular posts</h2>
        </div>
        {% endif %}
        {% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
		{% endif %}
        {% for paper in paper_list %}
            <div class="thumbnail">
                <div class="caption-full">
                    <h4>
                        <a href={% url 'paper:view_paper' paper.pid %}>{{ paper.title }}</a>
                        <small> {{ paper.begin_time }}</small>

                    </h4>
                    <small>
                        {% for tag in paper.tags %}
                            <a href={% url 'paper:tag_view' tag %}>#{{ tag }}&nbsp</a>
                        {% endfor %}
                    </small>
                    <p>{{ paper.desc }}</p>
                </div>
                <div>
                    {% if home %}
                    <a href="{% url 'paper:delete_paper' paper.pid %}" class="btn btn-sm btn-default">Delete</a>
                    {% else %}
                    <a href="{% url 'paper:like' paper.pid source %}" class="btn btn-sm btn-primary">&nbspLike&nbsp</a>
                    <a href="{% url 'paper:unlike' paper.pid source %}" class="btn btn-sm btn-primary">Unlike</a>
                    {% endif %}
                    <p class="pull-right text-primary">{{ paper.like }} like{{ paper.like|pluralize }}</p>
                </div>
            </div>
        {% endfor %}
    {% if home %}
        <div class="page_header">
	        <h2>My liked papers</h2>
        </div>
        {% if error_message2 %}
		<p><strong>{{ error_message2 }}</strong></p>
		{% endif %}
        {% for paper in liked_list %}
            <div class="thumbnail">
                <div class="caption-full">
                    <h4>
                        <a href={% url 'paper:view_paper' paper.pid %}>{{ paper.title }}</a>
                        <small> {{ paper.begin_time }}</small>

                    </h4>
                    <small>
                        {% for tag in paper.tags %}
                            <a href={% url 'paper:tag_view' tag %}>#{{ tag }}&nbsp</a>
                        {% endfor %}
                    </small>
                    <p>{{ paper.desc }}</p>
                </div>
                <div>
                    <a href="{% url 'paper:unlike' paper.pid source %}" class="btn btn-sm btn-primary">Unlike</a>
                    <p class="pull-right text-primary">{{ paper.like }} like{{ paper.like|pluralize }}</p>
                </div>
            </div>
        {% endfor %}
        <div class="page_header">
	        <h2>Recommendations</h2>
        </div>
        {% if error_message3 %}
		<p><strong>{{ error_message3 }}</strong></p>
		{% endif %}
        {% for paper in recommend_list %}
            <div class="thumbnail">
                <div class="caption-full">
                    <h4>
                        <a href={% url 'paper:view_paper' paper.pid %}>{{ paper.title }}</a>
                        <small> {{ paper.begin_time }}</small>

                    </h4>
                    <small>
                        {% for tag in paper.tags %}
                            <a href={% url 'paper:tag_view' tag %}>#{{ tag }}&nbsp</a>
                        {% endfor %}
                    </small>
                    <p>{{ paper.desc }}</p>
                </div>
                <div>
                    <a href="{% url 'paper:like' paper.pid source %}" class="btn btn-sm btn-primary">&nbspLike&nbsp</a>
                    <p class="pull-right text-primary">{{ paper.like }} like{{ paper.like|pluralize }}</p>
                </div>
            </div>
        {% endfor %}
    {% elif popular %}
        <div class="page_header">
	        <h2>Recent papers</h2>
        </div>
        {% if error_message2 %}
		<p><strong>{{ error_message2 }}</strong></p>
		{% endif %}
        {% for paper in recent_list %}
            <div class="thumbnail">
                <div class="caption-full">
                    <h4>
                        <a href={% url 'paper:view_paper' paper.pid %}>{{ paper.title }}</a>
                        <small> {{ paper.begin_time }}</small>

                    </h4>
                    <small>
                        {% for tag in paper.tags %}
                            <a href={% url 'paper:tag_view' tag %}>#{{ tag }}&nbsp</a>
                        {% endfor %}
                    </small>
                    <p>{{ paper.desc }}</p>
                </div>
                <div>
                    <a href="{% url 'paper:like' paper.pid source %}" class="btn btn-sm btn-primary">&nbspLike&nbsp</a>
                    <a href="{% url 'paper:unlike' paper.pid source %}" class="btn btn-sm btn-primary">Unlike</a>
                    <p class="pull-right text-primary">{{ paper.like }} like{{ paper.like|pluralize }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    </div>
{% endif %}
</div>
{% endblock %}

7/cmupaper/paper/templates/paper/login.html
{% extends "paper/base.html" %}

{% block body %}
<body>
  <div class="container">
    <div class="jumbotron">
    <form class="form-signin" role="form" action="{% url 'paper:login' %}" method='POST'>
      {% csrf_token %}
      <h2 class="form-signin-heading">Login</h2>
      {% if error_message %}
      <h3 class="form-signin-heading">{{ error_message }}</h3>
      {% endif %}
      <input type="text" class="form-control" name='username' placeholder="Username" required autofocus>
      <input type="password" class="form-control" name='password' placeholder="Password" required>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <a href="{% url 'paper:signup' %}" class="btn btn-lg btn-primary btn-block">Or sign up</a>
    </form>
  </div>
</body> 
{% endblock %}

7/cmupaper/paper/templates/paper/reset.html
{% extends "paper/base.html" %}

{% block body %}
<body>
  <div class="container">
    <div class="jumbotron">
        <h2 class="form-signin-heading">Reset {{ message }}!</h2>
    </div>
  </div>
</body> 
{% endblock %}

7/cmupaper/paper/templates/paper/signup.html
{% extends "paper/base.html" %}

{% block body %}
<body>
  <div class="container">
  <div class="jumbotron">
    <form class="form-signin" role="form" action="{% url 'paper:signup' %}" method='POST'>
      {% csrf_token %}
      <h2 class="form-signin-heading">Sign up</h2>
      {% if error_message %}
      <h3 class="form-signin-heading">{{ error_message }}</h3>
      {% endif %}
      <input type="text" class="form-control" name='username' placeholder="Username" required autofocus>
      <input type="password" class="form-control" name='password1' placeholder="Password" required>
      <input type="password" class="form-control" name='password2' placeholder="Password again" required>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
      <a href="{% url 'paper:login' %}" class="btn btn-lg btn-primary btn-block">Or sign in</a>
    </form>
  </div>
</body>
{% endblock %}